appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: V5my66wyqBt/j3IX/xxhP/pGvrj4tzvYwIklzcCZp+62QqI+oVwe2Nkk1g2n4R1leugEoMPkdposDvMFzmeiEK8PAsAe3DHeGzoPCIqZox+pQjShfSfTMLfdSZpadNtJc4qeCAkHOz2auHGNLcaKEnNzDBPNljvjjT5kiQo8tj7PkkiA1N0GxFKqKUavzRuFyiQBpwFT/3HsNP0VQKbgJvj6OKTr8xv3qHwgYdzIefx7TAEoO8mrP6cyQqXctnnOuUlCtrWEPC6k7y4pL8iQjdJ7YoRm7GJbc8SvkjmC5G2FeGQpCcqC39miuEnUF27g1dbZQQaAXLsAjsqabQ8NxtraoCDv86Yr6n/NcNFfuCBPv20TZnX6oNZ2la8PsvVE8qOkiaNVpnxNuSqtj+E+NG5VvXeYTcmH2ukBg+jGC/iF0nAG4KW6Id9Yj1U8JJiGTl7cvPrE+xc4IXWT6OL3IhPfVJLBMjgSUoX+7OOsPFW0MEOdzqAX71qm89sOdunbYSg2pZrNxGBfmqkWH8fWNpy6jDh6bOnWC4jduD8iaGx6cpTOK7uOjh8yGioPPKuqPzMXI6llOaSbZF2x0puRNapAEjf8ed0ENhC+RZgiOzBQlRU4mRrR+L4RT795u/z73HEM7b8kHDzL8cfllB20GWROf7KNMQ+zOJmLgUFWdOE=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
